version: "3.8"
services:
  backend:
    depends_on:
      - db
    build:
      context: .
      dockerfile: .Dockerfile
    environment:
      DB_HOST: db
      DB_NAME: postgres
    ports:
      - "8080:8080"
    networks:
      - bridge
    command: python src/app.py --host 0.0.0.0 --port 8080
    volumes:
      - backend_data:/src/images:rw  # Mount the persistent volume to store files
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    stdin_open: true
    tty: true
#    entrypoint: /bin/sh -c ".init_db.sh"

  db:
    image: postgres:15.4-alpine3.18
    restart: always
    ports:
      - "0.0.0.0:5444:5432"
    networks:
      - bridge
    volumes:
      - "./db/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    working_dir: /root

#  cache:
#    image: redis:6.2-alpine
#    restart: always
#    command: redis-server --save 20 1 --loglevel warning
#    volumes:
#      - session:/data
#    ports:
#      - "6380:6380"

  vectors:
    image: "redis/redis-stack-server"
    volumes:
      - ./redis_data:/data:rw
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    restart: always #unless-stopped

networks:
  bridge:
    driver: bridge

volumes:
  session:
    driver: local
  backend_data:

  redis_data:
